---
- hosts: all
  remote_user: root
  become: yes

  vars:
    db_name:     wordpress_db
    new_db_user: wordress_user
    new_db_pass: password
    domain:      wordpress.dev
    storage_dir: storage

  vars_files:
    - defaults/main.yml

  roles:
    - role: bbatsche.Base
    - role: bbatsche.MySQL-Manage
    - role: bbatsche.Phpenv
      dynamic_php: yes
      php_version: 7.0.6
      pecl_extensions: []

  tasks:
    - include: tasks/main.yml
