---
- name: Download
  get_url:
    url:  https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
    dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz

- name: Extract
  unarchive:
    src:  /tmp/wordpress-{{ wordpress_version }}.tar.gz
    dest: /tmp
    copy: no
    creates: /tmp/wordpress

- name: Install
  shell: cp -R /tmp/wordpress/* {{ http_root }}/{{ domain }}/public
  args:
    creates: "{{ http_root }}/{{ domain }}/public/index.php"

- name: Create Config
  command: >
    mv {{ http_root }}/{{ domain }}/public/wp-config-sample.php {{ http_root }}/{{ domain }}/public/wp-config.php
  args:
    creates: "{{ http_root }}/{{ domain }}/public/wp-config.php"

- name: Set Database Parameters
  lineinfile:
    dest: "{{ http_root }}/{{ domain }}/public/wp-config.php"
    line: "define('{{ item.key }}', '{{ item.value }}');"
    regexp: "define\\('{{ item.key }}',\\s*'.+'\\);"
  with_dict:
    DB_NAME: "{{ db_name }}"
    DB_USER: "{{ new_db_user }}"
    DB_PASSWORD: "{{ new_db_pass }}"
    DB_HOST: "{{ db_host }}"

- name: Set Auth Keys and Salts
  lineinfile:
    dest: "{{ http_root }}/{{ domain }}/public/wp-config.php"
    line: >
      define('{{ item }}',
      '{{ lookup('password', storage_dir + '/' + ansible_hostname + '/' + domain + '/' + item + ' length=64') }}');
    regexp: "define\\('{{ item }}',\\s*'.+'\\);"
  with_items:
    - AUTH_KEY
    - SECURE_AUTH_KEY
    - LOGGED_IN_KEY
    - NONCE_KEY
    - AUTH_SALT
    - SECURE_AUTH_SALT
    - LOGGED_IN_SALT
    - NONCE_SALT
